#include <stdio.h>
#include <gmp.h>
#include <sodium.h>

int main() {
    // Test GMP library
    printf("Testing GMP library...\n");
    mpz_t a, b, result;
    mpz_init(a);
    mpz_init(b);
    mpz_init(result);

    // Set values for a and b
    mpz_set_str(a, "1234567890123456789012345678901234567890", 10);
    mpz_set_str(b, "9876543210987654321098765432109876543210", 10);

    // Perform addition: result = a + b
    mpz_add(result, a, b);
    gmp_printf("GMP addition result: %Zd\n", result);
    mpz_sub(result, result, b);
    gmp_printf("GMP addition result: %Zd\n", result);

    // Clear memory
    mpz_clear(a);
    mpz_clear(b);
    mpz_clear(result);

    // Test Libsodium library
    printf("\nTesting Libsodium library...\n");
    if (sodium_init() < 0) {
        printf("Libsodium initialization failed!\n");
        return 1;
    }

    // Generate a random number using libsodium
    unsigned char random_number[32];
    randombytes_buf(random_number, sizeof(random_number));
    
    // Print the random number
    printf("Random number generated by Libsodium: ");
    for (int i = 0; i < 32; i++) {
        printf("%02x", random_number[i]);
    }
    printf("\n");

    printf("Libraries are working correctly!\n");
    return 0;
}
